server:  port: 8888management:  endpoint:    health:      show-details: always  endpoints:    web:      exposure:        include:        - '*'
logging:  level:    com.china: debug    org.nutz: debug    com.chinare: debugspring:  http:    encoding:      force-response: truerop:
  client:    app-key: test
    app-secret: 098f6bcd4621d373cade4e832627b4f6
    digest-name: SHA1
    endpoint: http://127.0.0.1:8888/rop.rest  server:
    digest-name: SHA1
    rop-path: rop.rest
    timeout: 100#    gate-way-uri: /gate